name:                swarm
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/tippenein/swarm#readme
license:             BSD3
author:              Brady Ouren
maintainer:          tippenein@gmail.com
copyright:           2021 Brady Ouren
extra-source-files:
- README.md


dependencies:
- base >= 4.7 && < 5
- gloss
- containers
- split
- random
- uuid
- uuid-types
- text

library:
  source-dirs: src

default-extensions:
  - OverloadedStrings
  - DeriveGeneric
  - NamedFieldPuns
  - RecordWildCards
  - DataKinds

executables:
  swarm:
    source-dirs: exe
    main: Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Werror
    dependencies:
    - swarm
